### ISSUE TITLE
希望可以设置企业微信应用消息类型

### ISSUE THREAD

**Issue by yqchilde** [lxk0301/jd_scripts#517]
## 期望增加的功能

A：当前企业微信应用消息支持图片消息，但是素材库的media_id有效期只有三天，每次更换很麻烦，可以给参数传递是否选择普通文本消息还是图片消息，以上是我的一点建议，作者辛苦了。

**Comment by hclasmn** [comment]
支持，建议还是用 上一版本，图文没有任何意义，虽然huang28的版本不支持图文，有512字节限制，但是足够了，还不需要点进去，要的不就是直接看么，何必再搞个可以点进去看的图文，media_id老是报错，很恶心了

**Comment by wunian588** [comment]
你在哪看见我邮箱的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: hclasmn <notifications@github.com&gt;
发送时间: 2021年1月3日 10:18
收件人: lxk0301/jd_scripts <jd_scripts@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[lxk0301/jd_scripts] 希望可以设置企业微信应用消息类型 (#517)





 
支持，建议还是用 上一版本，图文没有任何意义，虽然huang28的版本不支持图文，有512字节限制，但是足够了，还不需要点进去，要的不就是直接看么，何必再搞个可以点进去看的图文，media_id老是报错，很恶心了

**Comment by wunian588** [comment]
在哪看见我邮箱的

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Yqchilde <notifications@github.com&gt;
发送时间: 2021年1月3日 10:16
收件人: lxk0301/jd_scripts <jd_scripts@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[lxk0301/jd_scripts] 希望可以设置企业微信应用消息类型 (#517)





         
期望增加的功能
 
A：
 
入口
 
A：
 
当前企业微信应用消息支持图片消息，但是素材库的media_id有效期只有三天，每次更换很麻烦，可以给参数传递是否选择普通文本消息还是图片消息，以上是我的一点建议，作者辛苦了。

**Comment by hclasmn** [comment]
> 在哪看见我邮箱的 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: Yqchilde <notifications@github.com&gt; 发送时间: 2021年1月3日 10:16 收件人: lxk0301/jd_scripts <jd_scripts@noreply.github.com&gt; 抄送: Subscribed <subscribed@noreply.github.com&gt; 主题: 回复：[lxk0301/jd_scripts] 希望可以设置企业微信应用消息类型 (#517) 期望增加的功能 A： 入口 A： 当前企业微信应用消息支持图片消息，但是素材库的media_id有效期只有三天，每次更换很麻烦，可以给参数传递是否选择普通文本消息还是图片消息，以上是我的一点建议，作者辛苦了。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

你watch了，github推送给你的

**Comment by wunian588** [comment]
这个傻逼作者是不是写错邮箱了&nbsp;



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: hclasmn <notifications@github.com&gt;
发送时间: 2021年1月3日 10:21
收件人: lxk0301/jd_scripts <jd_scripts@noreply.github.com&gt;
抄送: wunian588 <977732711@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[lxk0301/jd_scripts] 希望可以设置企业微信应用消息类型 (#517)





  
在哪看见我邮箱的 发自我的iPhone
 …
 ------------------ 原始邮件 ------------------ 发件人: Yqchilde <notifications@github.com&gt; 发送时间: 2021年1月3日 10:16 收件人: lxk0301/jd_scripts <jd_scripts@noreply.github.com&gt; 抄送: Subscribed <subscribed@noreply.github.com&gt; 主题: 回复：[lxk0301/jd_scripts] 希望可以设置企业微信应用消息类型 (#517) 期望增加的功能 A： 入口 A： 当前企业微信应用消息支持图片消息，但是素材库的media_id有效期只有三天，每次更换很麻烦，可以给参数传递是否选择普通文本消息还是图片消息，以上是我的一点建议，作者辛苦了。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
你watch了，github推送给你的

**Comment by hclasmn** [comment]
![Screenshot_2021-01-03-10-30-31-62](https://user-images.githubusercontent.com/32213103/103470587-05643180-4daf-11eb-912e-ff3328702482.jpg)

**Comment by sxx1314** [comment]
**素材库 有效期是 永久的  只有你用临时api才是临时素材，那个才是三天有效期！**

详情见[#495](https://github.com/lxk0301/jd_scripts/pull/495)

**Comment by yqchilde** [comment]
> **素材库 有效期是 永久的 只有你用临时api才是临时素材，那个才是三天有效期！**
> 
> 详情见[#519](https://github.com/lxk0301/jd_scripts/issues/519) [#495](https://github.com/lxk0301/jd_scripts/pull/495)
> 
> 看不懂文档的请多看看合并时相应作者写的说明。

感谢指导！
